// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp1cfCFzBdh6uFYmmEPWjNUDsdqg1_1RU',
    appId: '1:297584821043:web:3b19bedf5d8dcce6ddf446',
    messagingSenderId: '297584821043',
    projectId: 'fir-auth-c456a',
    authDomain: 'fir-auth-c456a.firebaseapp.com',
    storageBucket: 'fir-auth-c456a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRzYa-ChkPx8Wsqz10m-d9Gxg12F83muk',
    appId: '1:297584821043:android:c42f553e74f0ef5cddf446',
    messagingSenderId: '297584821043',
    projectId: 'fir-auth-c456a',
    storageBucket: 'fir-auth-c456a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYvg-yNx1WNJlA5JYuOvo8MsuwH21_VCY',
    appId: '1:297584821043:ios:a3fcf3c5e4067b17ddf446',
    messagingSenderId: '297584821043',
    projectId: 'fir-auth-c456a',
    storageBucket: 'fir-auth-c456a.appspot.com',
    iosBundleId: 'com.tamil.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYvg-yNx1WNJlA5JYuOvo8MsuwH21_VCY',
    appId: '1:297584821043:ios:7ab34b7116af23dfddf446',
    messagingSenderId: '297584821043',
    projectId: 'fir-auth-c456a',
    storageBucket: 'fir-auth-c456a.appspot.com',
    iosBundleId: 'com.tamil.firebaseAuth.RunnerTests',
  );
}
